CREATE OR REPLACE TRANSIENT TABLE CRE_DB.CRE_LND.ASP_EVENT_LND (
	EVENT_ID VARCHAR(1000),
	RESERVATION_ID VARCHAR(1000),
	RESERVATION_STATUS VARCHAR(1000),
	STATUS_REASON VARCHAR(1000),
	START_TIME_ZONE VARCHAR(1000),
	END_TIME_ZONE VARCHAR(1000),
	RESERVATION_START_AT TIMESTAMP_NTZ(9),
	RESERVATION_END_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	TITLE VARCHAR(1000),
	RESOURCE_ID VARCHAR(1000),
	RESOURCE_TYPE VARCHAR(1000),
	RESOURCE_SUB_TYPE VARCHAR(1000),
	RESOURCE_NETWORK_NAME VARCHAR(1000),
	RESOURCE_FLOOR_NAME VARCHAR(1000),
	RESOURCE_NETWORK_ID VARCHAR(1000),
	RESOURCE_NAME VARCHAR(1000),
	RESOURCE_STATUS VARCHAR(1000),
	RECURRENCE_PATTERN_TYPE VARCHAR(100),
	RECURRENCE_RANGE_TYPE VARCHAR(100),
	RECURRENCE_START_DATE TIMESTAMP_NTZ(9),
	RECURRENCE_END_DATE TIMESTAMP_NTZ(9),
	NUMBER_OF_OCCURRENCES NUMBER(18,0),
	USER_ID VARCHAR(1000),
	EMAIL VARCHAR(1000),
	DISPLAY_NAME VARCHAR(1000),
	ATTENDEE_STATUS VARCHAR(1000),
	LOAD_BY VARCHAR(1000),
	LOAD_TIME TIMESTAMP_NTZ(9),
	TASK_NAME VARCHAR(1000),
	RUN_ID VARCHAR(1000)
)COMMENT='THIS TABLE CONTAINS THE EVENT API RELATED DATA POINTS'
;
-----------------------------------------------------
CREATE OR REPLACE TABLE CRE_DB.CRE_STG.ASP_EVENT_STG (
	EVENT_ID VARCHAR(1000),
	RESERVATION_ID VARCHAR(1000),
	RESERVATION_STATUS VARCHAR(1000),
	STATUS_REASON VARCHAR(1000),
	START_TIME_ZONE VARCHAR(1000),
	END_TIME_ZONE VARCHAR(1000),
	RESERVATION_START_AT TIMESTAMP_NTZ(9),
	RESERVATION_END_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	TITLE VARCHAR(1000),
	RESOURCE_ID VARCHAR(1000),
	RESOURCE_TYPE VARCHAR(1000),
	RESOURCE_SUB_TYPE VARCHAR(1000),
	RESOURCE_NETWORK_NAME VARCHAR(1000),
	RESOURCE_FLOOR_NAME VARCHAR(1000),
	RESOURCE_NETWORK_ID VARCHAR(1000),
	RESOURCE_NAME VARCHAR(1000),
	RESOURCE_STATUS VARCHAR(1000),
	RECURRENCE_PATTERN_TYPE VARCHAR(100),
	RECURRENCE_RANGE_TYPE VARCHAR(100),
	RECURRENCE_START_DATE TIMESTAMP_NTZ(9),
	RECURRENCE_END_DATE TIMESTAMP_NTZ(9),
	NUMBER_OF_OCCURRENCES NUMBER(18,0),
	USER_ID VARCHAR(1000),
	EMAIL VARCHAR(1000),
	DISPLAY_NAME VARCHAR(1000),
	ATTENDEE_STATUS VARCHAR(1000),
	TASK_NAME VARCHAR(1000),
	RUN_ID VARCHAR(1000),
	CREATED_BY VARCHAR(1000),
	CREATED_TIME TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(1000),
	UPDATED_TIME TIMESTAMP_NTZ(9)
)COMMENT='THIS TABLE CONTAINS THE EVENT API RELATED DATA POINTS'

;

CREATE OR REPLACE DYNAMIC TABLE CRE_DB.CRE_CORE.CRE_ASP_EVENT_CORE(
	EVENT_ID,
	RESERVATION_ID,
	RESERVATION_STATUS,
	STATUS_REASON,
	RESERVATION_START_AT,
	RESERVATION_END_AT,
	CREATED_AT,
	UPDATED_AT,
	TITLE,
	RESOURCE_ID,
	RESOURCE_TYPE,
	RESOURCE_SUB_TYPE,
	RESOURCE_NETWORK_NAME,
	RESOURCE_FLOOR_NAME,
	RESOURCE_NETWORK_ID,
	RESOURCE_NAME,
	RESOURCE_STATUS,
	USER_ID,
	EMAIL,
	DISPLAY_NAME,
	ATTENDEE_STATUS,
	CREATED_BY,
	CREATED_TIME,
	UPDATED_BY
)COMMENT='THIS THE FINAL TABLE CONTAINS SPACE AND DESK RELATED DATA'
;
----------------------------------------------------------------------
CREATE OR REPLACE TABLE CRE_DB.CRE_RPT.CRE_SU_NTH_EDH_TRR_ASP_KPI (
	L3_NAME VARCHAR(500),
	L3_PERNR VARCHAR(50),
	LENEL_BUILDING_ID VARCHAR(1000),
	APPSPACE_BUILDING_ID VARCHAR(1000),
	WORK_LOCATION_CODE VARCHAR(100),
	ASSIGNED_HEAD_COUNT NUMBER(18,0),
	CAPACITY NUMBER(38,12),
	COUNT_CORPORATE_UNASSIGNED NUMBER(38,12),
	CREATED_BY VARCHAR(1000),
	CREATED_TIME TIMESTAMP_LTZ(9),
	UPDATED_BY VARCHAR(1000)
)COMMENT='THIS TABLE CONTAINS THE EDH HEADCOUNT AND TRIRIGA CAPACITY INFORMATION WITH APPSPACE BUILDING NAME'
;
----------------------------------------------------------------------------
CREATE OR REPLACE TABLE CRE_DB.CRE_RPT.CRE_ASP_RESERVATION_KPI (
	EVENT_ID VARCHAR(1000),
	RESERVATION_ID VARCHAR(1000),
	RESERVATION_STATUS VARCHAR(1000),
	STATUS_REASON VARCHAR(1000),
	RESERVATION_START_AT VARCHAR(1000),
	RESERVATION_END_AT VARCHAR(1000),
	RESOURCE_ID VARCHAR(1000),
	RESOURCE_TYPE VARCHAR(1000),
	RESOURCE_SUB_TYPE VARCHAR(1000),
	RESOURCE_NETWORK_NAME VARCHAR(1000),
	RESOURCE_FLOOR_NAME VARCHAR(1000),
	RESOURCE_NETWORK_ID VARCHAR(1000),
	RESOURCE_NAME VARCHAR(1000),
	EMAIL VARCHAR(1000),
	DISPLAY_NAME VARCHAR(1000),
	PERNR VARCHAR(100),
	L3_NAME VARCHAR(1000),
	ASSIGNED_RESERVATION NUMBER(18,0)
)COMMENT='THIS TABLE CONTAINS ASSIGNED RESERVATION DATA'
;

CREATE OR REPLACE TABLE CRE_DB.CRE_RPT.CRE_WORKSPACE_RESERVATION_TAB (
	EVENT_ID VARCHAR(1000),
	RESERVATION_ID VARCHAR(1000),
	RESERVATION_STATUS VARCHAR(1000),
	RESERVATION_START_AT TIMESTAMP_NTZ(9),
	RESERVATION_END_AT TIMESTAMP_NTZ(9),
	RESOURCE_TYPE VARCHAR(1000),
	RESOURCE_SUB_TYPE VARCHAR(1000),
	RESERVATION_BUILDING_NAME VARCHAR(1000),
	RESOURCE_FLOOR_NAME VARCHAR(1000),
	RESOURCE_NAME VARCHAR(1000),
	EMAIL VARCHAR(1000),
	ATTENDEE_NAME VARCHAR(1000),
	L3_NAME VARCHAR(1000),
	PERNR VARCHAR(100),
	ASSIGNED_HEAD_COUNT NUMBER(18,0),
	CAPACITY NUMBER(38,12),
	ASSIGNED_RESERVATION NUMBER(18,0)
)COMMENT='THIS TABLE CONTAINS FINAL DATA FOR THE WORKSPACE RESERVATION DASHBOARD'
;

-----------------------------------------------------------------------
CREATE OR REPLACE dynamic table CRE_DB.CRE_CORE.CRE_ASP_EVENT_CORE(
	EVENT_ID,
	RESERVATION_ID,
	RESERVATION_STATUS,
	STATUS_REASON,
	RESERVATION_START_AT,
	RESERVATION_END_AT,
	CREATED_AT,
	UPDATED_AT,
	TITLE,
	RESOURCE_ID,
	RESOURCE_TYPE,
	RESOURCE_SUB_TYPE,
	RESOURCE_NETWORK_NAME,
	RESOURCE_FLOOR_NAME,
	RESOURCE_NETWORK_ID,
	RESOURCE_NAME,
	RESOURCE_STATUS,
	USER_ID,
	EMAIL,
	DISPLAY_NAME,
	ATTENDEE_STATUS,
	CREATED_BY,
	CREATED_TIME,
	UPDATED_BY
) target_lag = '5 minutes' refresh_mode = AUTO initialize = ON_CREATE warehouse = CRE_WH_ARCH_ADMIN_XS
 as
SELECT 
    EVENT_ID,
    RESERVATION_ID,
    RESERVATION_STATUS,
    STATUS_REASON,
     case when SNOWFLAKE_TIME_ZONE='America/Los_Angeles' then RESERVATION_START_AT

else CONVERT_TIMEZONE(SNOWFLAKE_TIME_ZONE, 'America/Los_Angeles', RESERVATION_START_AT) end  AS RESERVATION_START_AT,
    case when SNOWFLAKE_TIME_ZONE='America/Los_Angeles' then RESERVATION_END_AT

else CONVERT_TIMEZONE(SNOWFLAKE_TIME_ZONE, 'America/Los_Angeles', RESERVATION_END_AT) end  AS  RESERVATION_END_AT,
         case when SNOWFLAKE_TIME_ZONE='America/Los_Angeles' then CREATED_AT

else CONVERT_TIMEZONE(SNOWFLAKE_TIME_ZONE, 'America/Los_Angeles', CREATED_AT) end  AS  CREATED_AT,
            case when SNOWFLAKE_TIME_ZONE='America/Los_Angeles' then UPDATED_AT

else CONVERT_TIMEZONE(SNOWFLAKE_TIME_ZONE, 'America/Los_Angeles', UPDATED_AT) end  AS  UPDATED_AT,
    TITLE,
    RESOURCE_ID,
    RESOURCE_TYPE,
    RESOURCE_SUB_TYPE,
    RESOURCE_NETWORK_NAME,
    RESOURCE_FLOOR_NAME,
    RESOURCE_NETWORK_ID,
    RESOURCE_NAME,
    RESOURCE_STATUS,
    USER_ID,
    EMAIL,
    DISPLAY_NAME,
    ATTENDEE_STATUS,
    'SYSTEM' AS CREATED_BY,
    CURRENT_TIMESTAMP() AS CREATED_TIME,
    'SYSTEM' AS UPDATED_BY 
FROM CRE_DB.CRE_STG.ASP_EVENT_STG E
INNER JOIN CRE_DB.CRE_CORE.CRE_ASP_TIME_ZONE T
ON E.START_TIME_ZONE=T.ASP_TIME_VALUE
Where E.RESOURCE_TYPE='Space' and E.RESOURCE_SUB_TYPE='Desk'

------------------------------------------------------------------

CREATE OR REPLACE TASK CRE_DB.CRE_RPT.CRE_TSK_SU_NTH_EDH_TRR_ASP_KPI
	warehouse=CRE_WH_ARCH_ADMIN_XS
	schedule='USING CRON 30 3 * * * America/Los_Angeles'
	as BEGIN
    TRUNCATE TABLE CRE_DB.CRE_RPT.CRE_SU_NTH_EDH_TRR_ASP_KPI;
	
	INSERT INTO CRE_DB.CRE_RPT.CRE_SU_NTH_EDH_TRR_ASP_KPI
SELECT L3_NAME, L3_PERNR,LENEL_BUILDING_ID,APPSPACE_BUILDING_ID, WORK_LOCATION_CODE,
COUNT(DISTINCT PERNR) AS ASSIGNED_HEAD_COUNT,
CAPACITY,COALESCE(COUNT_CORPORATE_UNASSIGNED, 0) AS COUNT_CORPORATE_UNASSIGNED,CURRENT_USER() AS CREATED_BY,CURRENT_TIMESTAMP() AS CREATED_TIME,CURRENT_USER() AS UPDATED_BY FROM
CRE_DB.CRE_RPT.CRE_EDH_LEADER_NTH_HIER AA
LEFT JOIN
(SELECT SPACE_DEPARTMENT_LEADER_PERNR,SPACE_DEPARTMENT_LEADER,SAP_BUILDING_ID,LENEL_BUILDING_ID,APPSPACE_BUILDING_ID,
SUM(CASE WHEN SPACE_DEPARTMENT_LEADER <> '' THEN CAPACITY END) AS CAPACITY,
SUM(CASE WHEN SPACE_DEPARTMENT_LEADER = '' THEN CAPACITY END) AS COUNT_CORPORATE_UNASSIGNED
FROM
CRE_DB.CRE_CORE.CRE_TRR_PBFS_CORE
WHERE UPPER(SPACE_STATUS) <> 'RETIRED'
GROUP BY
SPACE_DEPARTMENT_LEADER_PERNR,
SPACE_DEPARTMENT_LEADER,
SAP_BUILDING_ID,
LENEL_BUILDING_ID,APPSPACE_BUILDING_ID) BB
ON
AA.L3_PERNR = BB.SPACE_DEPARTMENT_LEADER_PERNR
AND AA.WORK_LOCATION_CODE = BB.SAP_BUILDING_ID
WHERE UPPER(AA.EMPLOYMENT_STATUS_DESCRIPTION) IN ('ACTIVE')
GROUP BY
L3_NAME,
L3_PERNR,
LENEL_BUILDING_ID,
APPSPACE_BUILDING_ID,
WORK_LOCATION_CODE,
CAPACITY,
COALESCE(COUNT_CORPORATE_UNASSIGNED, 0);
END;
--------------------------------------------------------------
CREATE OR REPLACE TASK CRE_DB.CRE_RPT.CRE_TSK_ASP_RESERVATION_KPI
	warehouse=CRE_WH_ARCH_ADMIN_XS
	schedule='USING CRON 0 7 * * * America/Los_Angeles'
	as BEGIN
    TRUNCATE TABLE CRE_DB.CRE_RPT.CRE_ASP_RESERVATION_KPI;
    INSERT INTO CRE_DB.CRE_RPT.CRE_ASP_RESERVATION_KPI
    select  EVENT_ID,
	RESERVATION_ID,
	RESERVATION_STATUS,
	STATUS_REASON,
	RESERVATION_START_AT,
	RESERVATION_END_AT,
	RESOURCE_ID,
	RESOURCE_TYPE,
	RESOURCE_SUB_TYPE,
	RESOURCE_NETWORK_NAME,
	RESOURCE_FLOOR_NAME,
	RESOURCE_NETWORK_ID,
	RESOURCE_NAME,
	EMAIL,
	DISPLAY_NAME,
	edh.PERNR as PERNR,
	edh.l3_name ,
	CASE WHEN  edh.WORK_LOCATION_CODE IN (
                SELECT SAP_BUILDING_ID 
                FROM CRE_DB.CRE_CORE.VW_CRE_BUILDING_LOOKUP 
                WHERE APPSPACE_BUILDING_ID IN (
                    SELECT DISTINCT RESOURCE_NETWORK_NAME 
                    FROM CRE_DB.CRE_CORE.CRE_ASP_EVENT_CORE
                )
            ) THEN 1
            ELSE 0 
        END AS ASSIGNED_RESERVATION
	
	from CRE_DB.CRE_CORE.CRE_ASP_EVENT_CORE cr
left join CRE_DB.CRE_RPT.CRE_EDH_LEADER_NTH_HIER edh
on upper(cr.email)=upper(edh.work_email);
end;
----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CRE_DB.CRE_RPT.CRE_SP_ASP_PROCESS_ALL_BUILDINGS()
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python','requests')
HANDLER = 'process_building'
EXECUTE AS OWNER
AS '
from snowflake.snowpark import Session
def process_building(session: Session):
    try:
        # Get DISTINCT building names Reservation kpi table
        buildings_df = session.table("CRE_DB.CRE_RPT.CRE_ASP_RESERVATION_KPI") \\
                             .select("RESOURCE_NETWORK_NAME").distinct()
        buildings = buildings_df.collect()
        success_count = 0
        failure_count = 0
        error_messages = []
        for row in buildings:
            building_name = row["RESOURCE_NETWORK_NAME"]
            try:
                # Modified query to use building_name from ASP core table
                query = f"""
                    INSERT INTO CRE_DB.CRE_RPT.CRE_WORKSPACE_RESERVATION_TAB
                    SELECT 
                        CC.EVENT_ID, 
                        CC.RESERVATION_ID, 
                        CC.RESERVATION_STATUS,
                        CC.RESERVATION_START_AT, 
                        CC.RESERVATION_END_AT,
                        CC.RESOURCE_TYPE,
                        CC.RESOURCE_SUB_TYPE, 
                        CC.RESOURCE_NETWORK_NAME AS RESERVATION_BUILDING_NAME ,
                        CC.RESOURCE_FLOOR_NAME,
                        CC.RESOURCE_NAME,
                        CC.EMAIL ,
	                    CC.DISPLAY_NAME AS ATTENDEE_NAME ,
                        CC.L3_NAME,
                        CC.PERNR,
                        DD.ASSIGNED_HEAD_COUNT,
                        DD.CAPACITY,
                        CC.ASSIGNED_RESERVATION
                    FROM CRE_DB.CRE_RPT.CRE_ASP_RESERVATION_KPI CC
                    LEFT JOIN (
                        SELECT * 
                        FROM CRE_DB.CRE_RPT.CRE_SU_NTH_EDH_TRR_ASP_KPI
                        WHERE WORK_LOCATION_CODE IN (
                            SELECT SAP_BUILDING_ID 
                            FROM CRE_DB.CRE_CORE.VW_CRE_BUILDING_LOOKUP 
                            WHERE APPSPACE_BUILDING_ID = ''{building_name}''
                        )
                    ) DD
                    ON CC.L3_NAME = DD.L3_NAME
                    WHERE CC.RESOURCE_NETWORK_NAME = ''{building_name}'';
                """
                session.sql(query).collect()
                print(f"Processed building: {building_name}")
                success_count += 1
            except Exception as e:
                error_msg = f"Failed {building_name}: {str(e)}"
                print(error_msg)
                error_messages.append(error_msg)
                failure_count += 1
        result = f"Success: {success_count}, Failures: {failure_count}"
        if failure_count > 0:
            result += f"\\nErrors: {'', ''.join(error_messages[:5])}"  # Show first 5 errors
        return result
    except Exception as e:
        return f"Critical error: {str(e)}"
def run(session: Session) -> str:
    return process_building(session)
';
***********************************************************************************
CREATE OR REPLACE TASK CRE_DB.CRE_RPT.CRE_TSK_WORKSPACE_RESERVATION_TAB
	warehouse=CRE_WH_ARCH_ADMIN_XS
	schedule='USING CRON 0 1 * * * America/Los_Angeles'
	as BEGIN
TRUNCATE TABLE CRE_DB.CRE_RPT.CRE_WORKSPACE_RESERVATION_TAB;
CALL CRE_DB.CRE_RPT.CRE_SP_ASP_PROCESS_ALL_BUILDINGS();
END;



CREATE OR REPLACE STREAM NAABO_DEV.RR_REPORTING_WRITEBACK.ROPES_N_REPAIR_STREAM 
ON TABLE NAABO_DEV.RR_REPORTING_WRITEBACK."SIGDS_27259cad_15b0_46b3_8984_7ce243a6ef0e";

create or replace task NAABO_DEV.RR_REPORTING_WRITEBACK.ROPES_N_REPAIR_TASK
	warehouse=NAABO_DEV_WH
	when SYSTEM$STREAM_HAS_DATA('ROPES_N_REPAIR_STREAM')
	as CALL NAABO_DEV.RR_REPORTING_WRITEBACK.SP_GENERATE_ROPES_REPAIR();